CREATE DATABASE IF NOT EXISTS WAREHOUSE;
USE WAREHOUSE;

-- cities table
CREATE TABLE IF NOT EXISTS CITIES(
    CITY_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CITY CHAR(20) NOT NULL,
    STATE CHAR(20) NOT NULL
);

