CREATE DATABASE IF NOT EXISTS WAREHOUSE;
USE WAREHOUSE;

-- cities table
CREATE TABLE IF NOT EXISTS CITIES(
    CITY_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CITY CHAR(20) NOT NULL,
    STATE CHAR(20) NOT NULL
);

-- Warehouses table
CREATE TABLE IF NOT EXISTS WAREHOUSES(
    WAREHOUSE_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    WAREHOUSE_NAME CHAR(30) NOT NULL,
    LOCATION CHAR(20) NOT NULL,
    EXTRA_CONTEXT JSON,
    CITY_ID INTEGER NOT NULL,
    FOREIGN KEY (CITY_ID) REFERENCES CITIES(CITY_ID)
);

-- STORES table
CREATE TABLE IF NOT EXISTS STORES(
    STORE_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STORE_NAME CHAR(20) NOT NULL,
    LOCATION_CITY CHAR(20) NOT NULL,
    WAREHOUSE_ID INTEGER NOT NULL,
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID)
);

-- CUSTOMERS table
CREATE TABLE IF NOT EXISTS CUSTOMERS(
    CUSTOMER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME CHAR(50) NOT NULL,
    ADDR VARCHAR(50) NOT NULL,
    CUSTOMER_CITY CHAR(20) NOT NULL
);

-- ORDERS table
CREATE TABLE IF NOT EXISTS ORDERS(
    ORDER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ORDER_DATE DATETIME NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);


-- ITEMS table
CREATE TABLE IF NOT EXISTS ITEMS(
    ITEM_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    DESCRIPTION TEXT NOT NULL,
    WEIGHT DECIMAL(5, 2) NOT NULL,
    COST DECIMAL(5, 2) NOT NULL
);


-- ITEMS_ORDERS table
CREATE TABLE IF NOT EXISTS ITEMS_ORDERS(
    ITEM_ORDER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ORDERED_QUANTITY INTEGER NOT NULL,
    ORDER_ID INTEGER NOT NULL,
    ITEM_ID INTEGER NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ITEM_ID)
);

-- STORES_ITEMS table
CREATE TABLE IF NOT EXISTS STORES_ITEMS(
    STORE_ITEM_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    QUANTITY INTEGER NOT NULL,
    STORE_ID INTEGER NOT NULL,
    ITEM_ID INTEGER NOT NULL,
    FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ITEM_ID)
);

-- insert some values 
INSERT INTO CITIES VALUES ('Pune', 'Maharashtra');
INSERT INTO CITIES VALUES ('Vadodara', 'Gujarat');
INSERT INTO ITEMS VALUES (1, "KEYBOARD", 250.00, 500.00);
INSERT INTO ITEMS VALUES (2, "MOUSE", 100.00, 300.00);
INSERT INTO WAREHOUSES VALUES (1, "WEST WAREHOUSE", "Highway", 'Pune');
INSERT INTO WAREHOUSES VALUES (2, "Amazon warehouse", "Cross road", 'Vadodara');
INSERT INTO WAREHOUSES VALUES (3, "Flipkart warehouse", "City center", 'Pune');
INSERT INTO CUSTOMER VALUES(1, "Patil", "Opp City Hospital, India", 'Pune');
INSERT INTO CUSTOMER VALUES(2, "Patel", "Near Railway Station, India", 'Vadodara');
INSERT INTO CUSTOMER VALUES(3, "Shrivastav", "Twin towers, India", 'Pune');
INSERT INTO ORDERINFO VALUES(1,  1, '2022-10-05');
INSERT INTO ORDERINFO VALUES(2,  1, '2022-10-05');
INSERT INTO ORDERINFO VALUES(3,  2, '2022-10-05');
INSERT INTO ITEMS_ORDERED VALUES(1, "KEYBOARD", 1, 5);
INSERT INTO ITEMS_ORDERED VALUES(2, "MOUSE", 1, 5);
INSERT INTO ITEMS_ORDERED VALUES(1, "KEYBOARD", 2, 10);
INSERT INTO ITEMS_ORDERED VALUES(2, "MOUSE", 3, 15);
INSERT INTO STORES VALUES(1, "D-Mart", "Pune", 1);
INSERT INTO STORES VALUES(2, "Jio-Mart", "Vadodara", 2);
INSERT INTO STORES VALUES(3, "D-Mart", "Vadodara", 1);
INSERT INTO STORE_ITEMS VALUES (1, 1, 50);
INSERT INTO STORE_ITEMS VALUES (2, 1, 100);
INSERT INTO STORE_ITEMS VALUES (1, 2, 125);
